<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MandalSeeder extends Seeder
{
    public function run()
    {
        $items = [
        ['id' => 48870,'census_name' => 'Addateegala', 'name' => 'Addateegala', 'district_id' => 5440],
        ['id' => 48450,'census_name' => 'Ananthagiri', 'name' => 'Ananthagiri', 'district_id' => 5440],
        ['id' => 48440,'census_name' => 'Araku Valley', 'name' => 'Araku Valley', 'district_id' => 5440],
        ['id' => 48490,'census_name' => 'Chintapalle', 'name' => 'Chintapalle', 'district_id' => 5440],
        ['id' => 47320,'census_name' => 'Chintur', 'name' => 'Chintur', 'district_id' => 5440],
        ['id' => 48850,'census_name' => 'Devipatnam', 'name' => 'Devipatnam', 'district_id' => 5440],
        ['id' => 48430,'census_name' => 'Dumbriguda', 'name' => 'Dumbriguda', 'district_id' => 5440],
        ['id' => 47321,'census_name' => 'Chintur', 'name' => 'Etapaka', 'district_id' => 5440],
        ['id' => 48480,'census_name' => 'G.Madugula', 'name' => 'Ganagaraju Madugula', 'district_id' => 5440],
        ['id' => 48940,'census_name' => 'Gangavaram', 'name' => 'Gangavaram', 'district_id' => 5440],
        ['id' => 48500,'census_name' => 'Gudem Kotha Veedhi', 'name' => 'Gudem Kotha Veedhi', 'district_id' => 5440],
        ['id' => 48460,'census_name' => 'Hukumpeta', 'name' => 'Hukumpeta', 'district_id' => 5440],
        ['id' => 48510,'census_name' => 'Koyyuru', 'name' => 'Koyyuru', 'district_id' => 5440],
        ['id' => 47310,'census_name' => 'Kunavaram', 'name' => 'Kunavaram', 'district_id' => 5440],
        ['id' => 48840,'census_name' => 'Maredumilli', 'name' => 'Maredumilli', 'district_id' => 5440],
        ['id' => 48410,'census_name' => 'Munchingi Puttu', 'name' => 'Munchingi Puttu', 'district_id' => 5440],
        ['id' => 48470,'census_name' => 'Paderu', 'name' => 'Paderu', 'district_id' => 5440],
        ['id' => 48420,'census_name' => 'Peda Bayalu', 'name' => 'Peda Bayalu', 'district_id' => 5440],
        ['id' => 48880,'census_name' => 'Rajavommangi', 'name' => 'Rajavommangi', 'district_id' => 5440],
        ['id' => 48950,'census_name' => 'Rampachodavaram', 'name' => 'Rampachodavaram', 'district_id' => 5440],
        ['id' => 47330,'census_name' => 'Vararamachandrapuram', 'name' => 'Vararamachandrapuram', 'district_id' => 5440],
        ['id' => 48860,'census_name' => 'Y. Ramavaram', 'name' => 'Y. Ramavaram', 'district_id' => 5440],
        ['id' => 48710,'census_name' => 'Anakapalle', 'name' => 'Anakapalle', 'district_id' => 5441],
        ['id' => 48780,'census_name' => 'Atchutapuram', 'name' => 'Atchutapuram', 'district_id' => 5441],
        ['id' => 48730,'census_name' => 'Butchayyapeta', 'name' => 'Butchayyapeta', 'district_id' => 5441],
        ['id' => 48580,'census_name' => 'Cheedikada', 'name' => 'Cheedikada', 'district_id' => 5441],
        ['id' => 48720,'census_name' => 'Chodavaram', 'name' => 'Chodavaram', 'district_id' => 5441],
        ['id' => 48590,'census_name' => 'Devarapalle', 'name' => 'Devarapalli', 'district_id' => 5441],
        ['id' => 48790,'census_name' => 'Yelamanchili', 'name' => 'Elamanchili', 'district_id' => 5441],
        ['id' => 48530,'census_name' => 'Golugonda', 'name' => 'Golugonda', 'district_id' => 5441],
        ['id' => 48600,'census_name' => 'K.Kotapadu', 'name' => 'K.Kotapadu', 'district_id' => 5441],
        ['id' => 48760,'census_name' => 'Kasimkota', 'name' => 'Kasimkota', 'district_id' => 5441],
        ['id' => 48740,'census_name' => 'Kotauratla', 'name' => 'Kotauratla', 'district_id' => 5441],
        ['id' => 48570,'census_name' => 'Madugula', 'name' => 'Madugula', 'district_id' => 5441],
        ['id' => 48750,'census_name' => 'Makavarapalem', 'name' => 'Makavarapalem', 'district_id' => 5441],
        ['id' => 48770,'census_name' => 'Munagapaka', 'name' => 'Munagapaka', 'district_id' => 5441],
        ['id' => 48800,'census_name' => 'Nakkapalle', 'name' => 'Nakkapalle', 'district_id' => 5441],
        ['id' => 48540,'census_name' => 'Narsipatnam', 'name' => 'Narsipatnam', 'district_id' => 5441],
        ['id' => 48520,'census_name' => 'Nathavaram', 'name' => 'Nathavaram', 'district_id' => 5441],
        ['id' => 48700,'census_name' => 'Paravada', 'name' => 'Paravada', 'district_id' => 5441],
        ['id' => 48810,'census_name' => 'Payakaraopeta', 'name' => 'Payakaraopeta Mandal', 'district_id' => 5441],
        ['id' => 48830,'census_name' => 'Rambilli', 'name' => 'Rambilli', 'district_id' => 5441],
        ['id' => 48560,'census_name' => 'Ravikamatham', 'name' => 'Ravikamatham', 'district_id' => 5441],
        ['id' => 48550,'census_name' => 'Rolugunta', 'name' => 'Rolugunta', 'district_id' => 5441],
        ['id' => 48820,'census_name' => 'S.Rayavaram', 'name' => 'Sarvasiddhi Rayavaram', 'district_id' => 5441],
        ['id' => 48610,'census_name' => 'Sabbavaram', 'name' => 'Sabbavaram', 'district_id' => 5441],
        ['id' => 53300,'census_name' => 'Anantapur', 'name' => 'Anantapur Urban', 'district_id' => 5530],
        ['id' => 53301,'census_name' => 'Anantapur', 'name' => 'Anantapur Rural', 'district_id' => 5530],
        ['id' => 45920,'census_name' => 'Atmakur', 'name' => 'Atmakur', 'district_id' => 5530],
        ['id' => 53180,'census_name' => 'Beluguppa', 'name' => 'Beluguppa', 'district_id' => 5530],
        ['id' => 53070,'census_name' => 'Bommanahal', 'name' => 'Bommanahal', 'district_id' => 5530],
        ['id' => 53200,'census_name' => 'Brahmasamudram', 'name' => 'Brahmasamudram', 'district_id' => 5530],
        ['id' => 53290,'census_name' => 'Bukkaraya Samudram', 'name' => 'Bukkaraya Samudram', 'district_id' => 5530],
        ['id' => 53040,'census_name' => 'D.Hirehal', 'name' => 'D.Hirehal', 'district_id' => 5530],
        ['id' => 53240,'census_name' => 'Garladinne', 'name' => 'Garladinne', 'district_id' => 5530],
        ['id' => 53100,'census_name' => 'Gooty', 'name' => 'Gooty', 'district_id' => 5530],
        ['id' => 53190,'census_name' => 'Gummagatta', 'name' => 'Gummagatta', 'district_id' => 5530],
        ['id' => 53090,'census_name' => 'Guntakal', 'name' => 'Guntakal', 'district_id' => 5530],
        ['id' => 53210,'census_name' => 'Kalyandurg', 'name' => 'Kalyandurg', 'district_id' => 5530],
        ['id' => 53340,'census_name' => 'Kambadur', 'name' => 'Kambadur', 'district_id' => 5530],
        ['id' => 53060,'census_name' => 'Kanekal', 'name' => 'Kanekal', 'district_id' => 5530],
        ['id' => 53230,'census_name' => 'Kudair', 'name' => 'Kudair', 'district_id' => 5530],
        ['id' => 53330,'census_name' => 'Kundurpi', 'name' => 'Kundurpi', 'district_id' => 5530],
        ['id' => 53280,'census_name' => 'Narpala', 'name' => 'Narpala', 'district_id' => 5530],
        ['id' => 53150,'census_name' => 'Pamidi', 'name' => 'Pamidi', 'district_id' => 5530],
        ['id' => 53140,'census_name' => 'Peddapappur', 'name' => 'Peddapappur', 'district_id' => 5530],
        ['id' => 53110,'census_name' => 'Peddavadugur', 'name' => 'Peddavadugur', 'district_id' => 5530],
        ['id' => 53260,'census_name' => 'Putlur', 'name' => 'Putlur', 'district_id' => 5530],
        ['id' => 53310,'census_name' => 'Raptadu', 'name' => 'Raptadu', 'district_id' => 5530],
        ['id' => 53050,'census_name' => 'Rayadurg', 'name' => 'Rayadurg', 'district_id' => 5530],
        ['id' => 53320,'census_name' => 'Settur', 'name' => 'Settur', 'district_id' => 5530],
        ['id' => 53250,'census_name' => 'Singanamala', 'name' => 'Singanamala', 'district_id' => 5530],
        ['id' => 53130,'census_name' => 'Tadpatri', 'name' => 'Tadpatri', 'district_id' => 5530],
        ['id' => 53170,'census_name' => 'Uravakonda', 'name' => 'Uravakonda', 'district_id' => 5530],
        ['id' => 53160,'census_name' => 'Vajrakarur', 'name' => 'Vajrakarur', 'district_id' => 5530],
        ['id' => 53080,'census_name' => 'Vidapanakal', 'name' => 'Vidapanakal', 'district_id' => 5530],
        ['id' => 53120,'census_name' => 'Yadiki', 'name' => 'Yadiki', 'district_id' => 5530],
        ['id' => 53270,'census_name' => 'Yellanur', 'name' => 'Yellanur', 'district_id' => 5530],
        ['id' => 53910,'census_name' => 'B.Kothakota', 'name' => 'Beerangi Kothakota', 'district_id' => 5540],
        ['id' => 52360,'census_name' => 'Chinnamandem', 'name' => 'Chinnamandyam', 'district_id' => 5540],
        ['id' => 52450,'census_name' => 'Chitvel', 'name' => 'Chitvel', 'district_id' => 5540],
        ['id' => 52350,'census_name' => 'Galiveedu', 'name' => 'Galiveedu', 'district_id' => 5540],
        ['id' => 53700,'census_name' => 'Gurramkonda', 'name' => 'Gurramkonda', 'district_id' => 5540],
        ['id' => 53710,'census_name' => 'Kalakada', 'name' => 'Kalakada', 'district_id' => 5540],
        ['id' => 53870,'census_name' => 'Kalikiri', 'name' => 'Kalikiri', 'district_id' => 5540],
        ['id' => 53720,'census_name' => 'Kambhamvaripalle', 'name' => 'Kambhamvaripalle', 'district_id' => 5540],
        ['id' => 50390,'census_name' => 'Koduru', 'name' => 'Railway Koduru', 'district_id' => 5540],
        ['id' => 53890,'census_name' => 'Kurabalakota', 'name' => 'Kurabalakota', 'district_id' => 5540],
        ['id' => 52400,'census_name' => 'Lakkireddipalle', 'name' => 'Lakkireddypalle', 'district_id' => 5540],
        ['id' => 53920,'census_name' => 'Madanapalle', 'name' => 'Madanapalle', 'district_id' => 5540],
        ['id' => 53670,'census_name' => 'Mulakalacheruvu', 'name' => 'Mulakalacheruvu', 'district_id' => 5540],
        ['id' => 52430,'census_name' => 'Nandalur', 'name' => 'Nandalur', 'district_id' => 5540],
        ['id' => 53930,'census_name' => 'Nimmanapalle', 'name' => 'Nimmanapalle', 'district_id' => 5540],
        ['id' => 52480,'census_name' => 'Obulavaripalle', 'name' => 'Obulavaripalle', 'district_id' => 5540],
        ['id' => 53900,'census_name' => 'Pedda Thippasamudram', 'name' => 'Pedda Thippasamudram', 'district_id' => 5540],
        ['id' => 53690,'census_name' => 'Peddamandyam', 'name' => 'Peddamandyam', 'district_id' => 5540],
        ['id' => 52440,'census_name' => 'Penagalur', 'name' => 'Penagalur', 'district_id' => 5540],
        ['id' => 53860,'census_name' => 'Pileru', 'name' => 'Pileru', 'district_id' => 5540],
        ['id' => 52470,'census_name' => 'Pullampeta', 'name' => 'Pullampeta', 'district_id' => 5540],
        ['id' => 52460,'census_name' => 'Rajampet', 'name' => 'Rajampet', 'district_id' => 5540],
        ['id' => 52410,'census_name' => 'Ramapuram', 'name' => 'Ramapuram', 'district_id' => 5540],
        ['id' => 54140,'census_name' => 'Ramasamudram', 'name' => 'Ramasamudram', 'district_id' => 5540],
        ['id' => 52390,'census_name' => 'Rayachoti', 'name' => 'Rayachoti', 'district_id' => 5540],
        ['id' => 52370,'census_name' => 'Sambepalle', 'name' => 'Sambepalli', 'district_id' => 5540],
        ['id' => 52380,'census_name' => 'T Sundupalle', 'name' => 'T Sundupalle', 'district_id' => 5540],
        ['id' => 53680,'census_name' => 'Thamballapalle', 'name' => 'Thamballapalle', 'district_id' => 5540],
        ['id' => 53880,'census_name' => 'Valmikipuram', 'name' => 'Valmikipuram', 'district_id' => 5540],
        ['id' => 52420,'census_name' => 'Veeraballe', 'name' => 'Veeraballi', 'district_id' => 5540],
        ['id' => 51120,'census_name' => 'Addanki', 'name' => 'Addanki', 'district_id' => 5490],
        ['id' => 50860,'census_name' => 'Amruthalur', 'name' => 'Amruthalur', 'district_id' => 5490],
        ['id' => 51050,'census_name' => 'Ballikurava', 'name' => 'Ballikurava', 'district_id' => 5490],
        ['id' => 50930,'census_name' => 'Bapatla', 'name' => 'Bapatla', 'district_id' => 5490],
        ['id' => 50890,'census_name' => 'Bhattiprolu', 'name' => 'Bhattiprolu', 'district_id' => 5490],
        ['id' => 50900,'census_name' => 'Cherukupalle H/O Arumbaka', 'name' => 'Cherukupalle', 'district_id' => 5490],
        ['id' => 51250,'census_name' => 'Chinaganjam', 'name' => 'Chinaganjam', 'district_id' => 5490],
        ['id' => 51230,'census_name' => 'Chirala', 'name' => 'Chirala', 'district_id' => 5490],
        ['id' => 51100,'census_name' => 'Inkollu', 'name' => 'Inkollu', 'district_id' => 5490],
        ['id' => 51110,'census_name' => 'Janakavarampanguluru', 'name' => 'Janakavarampanguluru', 'district_id' => 5490],
        ['id' => 51090,'census_name' => 'Karamchedu', 'name' => 'Karamchedu', 'district_id' => 5490],
        ['id' => 50920,'census_name' => 'Karlapalem', 'name' => 'Karlapalem', 'district_id' => 5490],
        ['id' => 50880,'census_name' => 'Kollur', 'name' => 'Kolluru', 'district_id' => 5490],
        ['id' => 51220,'census_name' => 'Korisapadu', 'name' => 'Korisapadu', 'district_id' => 5490],
        ['id' => 51060,'census_name' => 'Martur', 'name' => 'Martur', 'district_id' => 5490],
        ['id' => 50950,'census_name' => 'Nagaram', 'name' => 'Nagaram', 'district_id' => 5490],
        ['id' => 50940,'census_name' => 'Nizampatnam', 'name' => 'Nizampatnam', 'district_id' => 5490],
        ['id' => 51080,'census_name' => 'Parchur', 'name' => 'Parchur', 'district_id' => 5490],
        ['id' => 50910,'census_name' => 'Pittalavanipalem', 'name' => 'Pittalavanipalem', 'district_id' => 5490],
        ['id' => 50960,'census_name' => 'Repalle', 'name' => 'Repalle', 'district_id' => 5490],
        ['id' => 51040,'census_name' => 'Santhamaguluru', 'name' => 'Santhamaguluru', 'district_id' => 5490],
        ['id' => 50850,'census_name' => 'Tsundur', 'name' => 'Tsundur', 'district_id' => 5490],
        ['id' => 50870,'census_name' => 'Vemuru', 'name' => 'Vemuru', 'district_id' => 5490],
        ['id' => 51240,'census_name' => 'Vetapalem', 'name' => 'Vetapalem', 'district_id' => 5490],
        ['id' => 51070,'census_name' => 'Yeddana Pudi', 'name' => 'Yeddanapudi', 'district_id' => 5490],
        ['id' => 54230,'census_name' => 'Baireddipalle', 'name' => 'Baireddipalle', 'district_id' => 5541],
        ['id' => 54290,'census_name' => 'Bangarupalem', 'name' => 'Bangarupalem', 'district_id' => 5541],
        ['id' => 54210,'census_name' => 'Chittoor', 'name' => 'Chittoor Rural', 'district_id' => 5541],
        ['id' => 54211,'census_name' => 'Chittoor', 'name' => 'Chittoor Urban', 'district_id' => 5541],
        ['id' => 54130,'census_name' => 'Chowdepalle', 'name' => 'Chowdepalle', 'district_id' => 5541],
        ['id' => 54200,'census_name' => 'Gangadhara Nellore', 'name' => 'Gangadhara Nellore', 'district_id' => 5541],
        ['id' => 54310,'census_name' => 'Gudipala', 'name' => 'Gudipala', 'district_id' => 5541],
        ['id' => 54260,'census_name' => 'Gudupalle', 'name' => 'Gudupalle', 'district_id' => 5541],
        ['id' => 54110,'census_name' => 'Irala', 'name' => 'Irala', 'district_id' => 5541],
        ['id' => 54080,'census_name' => 'Karvetinagar', 'name' => 'Karvetinagar', 'district_id' => 5541],
        ['id' => 54270,'census_name' => 'Kuppam', 'name' => 'Kuppam', 'district_id' => 5541],
        ['id' => 54060,'census_name' => 'Nagari', 'name' => 'Nagari', 'district_id' => 5541],
        ['id' => 54040,'census_name' => 'Nindra', 'name' => 'Nindra', 'district_id' => 5541],
        ['id' => 54220,'census_name' => 'Palamaner', 'name' => 'Palamaner', 'district_id' => 5541],
        ['id' => 54320,'census_name' => 'Palasamudram', 'name' => 'Palasamudram', 'district_id' => 5541],
        ['id' => 54160,'census_name' => 'Peddapanjani', 'name' => 'Peddapanjani', 'district_id' => 5541],
        ['id' => 54090,'census_name' => 'Penumuru', 'name' => 'Penumuru', 'district_id' => 5541],
        ['id' => 53950,'census_name' => 'Pulicherla', 'name' => 'Pulicherla', 'district_id' => 5541],
        ['id' => 54150,'census_name' => 'Punganur', 'name' => 'Punganur', 'district_id' => 5541],
        ['id' => 54100,'census_name' => 'Puthalapattu', 'name' => 'Puthalapattu', 'district_id' => 5541],
        ['id' => 54280,'census_name' => 'Ramakuppam', 'name' => 'Ramakuppam', 'district_id' => 5541],
        ['id' => 50660,'census_name' => 'Rompicherla', 'name' => 'Rompicherla', 'district_id' => 5541],
        ['id' => 54250,'census_name' => 'Santhipuram', 'name' => 'Santhipuram', 'district_id' => 5541],
        ['id' => 53940,'census_name' => 'Sodam', 'name' => 'Sodam', 'district_id' => 5541],
        ['id' => 54120,'census_name' => 'Somala', 'name' => 'Somala', 'district_id' => 5541],
        ['id' => 54190,'census_name' => 'Srirangarajapuram', 'name' => 'Srirangarajapuram', 'district_id' => 5541],
        ['id' => 54180,'census_name' => 'Thavanampalle', 'name' => 'Thavanampalle', 'district_id' => 5541],
        ['id' => 53970,'census_name' => 'Vedurukuppam', 'name' => 'Vedurukuppam', 'district_id' => 5541],
        ['id' => 54240,'census_name' => 'Venkatagirikota', 'name' => 'Venkatagirikota', 'district_id' => 5541],
        ['id' => 54050,'census_name' => 'Vijayapuram', 'name' => 'Vijayapuram', 'district_id' => 5541],
        ['id' => 54300,'census_name' => 'Yadamarri', 'name' => 'Yadamarri', 'district_id' => 5541],
        ['id' => 49170,'census_name' => 'Anaparthy', 'name' => 'Anaparthi', 'district_id' => 5450],
        ['id' => 49160,'census_name' => 'Biccavolu', 'name' => 'Biccavolu', 'district_id' => 5450],
        ['id' => 49590,'census_name' => 'Chagallu', 'name' => 'Chagallu', 'district_id' => 5450],
        ['id' => 48591,'census_name' => 'Devarapalle', 'name' => 'Devarapalle', 'district_id' => 5450],
        ['id' => 48970,'census_name' => 'Gokavaram', 'name' => 'Gokavaram', 'district_id' => 5450],
        ['id' => 49510,'census_name' => 'Gopalapuram', 'name' => 'Gopalapuram', 'district_id' => 5450],
        ['id' => 49180,'census_name' => 'Kadiam', 'name' => 'Kadiam', 'district_id' => 5450],
        ['id' => 49050,'census_name' => 'Korukonda', 'name' => 'Korukonda Mandal', 'district_id' => 5450],
        ['id' => 49580,'census_name' => 'Kovvur', 'name' => 'Kovvur', 'district_id' => 5450],
        ['id' => 49560,'census_name' => 'Nallajerla', 'name' => 'Nallajerla', 'district_id' => 5450],
        ['id' => 49600,'census_name' => 'Nidadavole', 'name' => 'Nidadavole', 'district_id' => 5450],
        ['id' => 49710,'census_name' => 'Peravali', 'name' => 'Peravali', 'district_id' => 5450],
        ['id' => 49060,'census_name' => 'Rajahmundry (Urban)', 'name' => 'Rajahmundry Urban', 'district_id' => 5450],
        ['id' => 49070,'census_name' => 'Rajahmundry Rural', 'name' => 'Rajahmundry Rural', 'district_id' => 5450],
        ['id' => 49080,'census_name' => 'Rajanagaram', 'name' => 'Rajanagaram', 'district_id' => 5450],
        ['id' => 49090,'census_name' => 'Rangampeta', 'name' => 'Rangampeta', 'district_id' => 5450],
        ['id' => 48140,'census_name' => 'Seethanagaram', 'name' => 'Seethanagaram', 'district_id' => 5450],
        ['id' => 49500,'census_name' => 'Tallapudi', 'name' => 'Tallapudi', 'district_id' => 5450],
        ['id' => 49700,'census_name' => 'Undrajavaram', 'name' => 'Undrajavaram', 'district_id' => 5450],
        ['id' => 50050,'census_name' => 'Agiripalle', 'name' => 'Agiripalle', 'district_id' => 5460],
        ['id' => 49630,'census_name' => 'Bhimadole', 'name' => 'Bhimadole', 'district_id' => 5460],
        ['id' => 49480,'census_name' => 'Buttayagudem', 'name' => 'Buttayagudem', 'district_id' => 5460],
        ['id' => 50010,'census_name' => 'Chatrai', 'name' => 'Chatrai', 'district_id' => 5460],
        ['id' => 49440,'census_name' => 'Chintalapudi', 'name' => 'Chintalapudi', 'district_id' => 5460],
        ['id' => 49670,'census_name' => 'Denduluru', 'name' => 'Denduluru', 'district_id' => 5460],
        ['id' => 49550,'census_name' => 'Dwarakatirumala', 'name' => 'Dwaraka Tirumala', 'district_id' => 5460],
        ['id' => 49660,'census_name' => 'Eluru', 'name' => 'Eluru', 'district_id' => 5460],
        ['id' => 49530,'census_name' => 'Jangareddigudem', 'name' => 'Jangareddygudem', 'district_id' => 5460],
        ['id' => 49470,'census_name' => 'Jeelugu Milli', 'name' => 'Jeelugu Milli', 'district_id' => 5460],
        ['id' => 50160,'census_name' => 'Kaikalur', 'name' => 'Kaikalur', 'district_id' => 5460],
        ['id' => 50170,'census_name' => 'Kalidindi', 'name' => 'Kalidindi', 'district_id' => 5460],
        ['id' => 49540,'census_name' => 'Kamavarapukota', 'name' => 'Kamavarapukota', 'district_id' => 5460],
        ['id' => 49520,'census_name' => 'Koyyalagudem', 'name' => 'Koyyalagudem', 'district_id' => 5460],
        ['id' => 47350,'census_name' => 'Kukunoor', 'name' => 'Kukunoor', 'district_id' => 5460],
        ['id' => 49450,'census_name' => 'Lingapalem', 'name' => 'Lingapalem', 'district_id' => 5460],
        ['id' => 50150,'census_name' => 'Mandavalli', 'name' => 'Mandavalli', 'district_id' => 5460],
        ['id' => 50200,'census_name' => 'Mudinepalle', 'name' => 'Mudinepalle', 'district_id' => 5460],
        ['id' => 50020,'census_name' => 'Musunuru', 'name' => 'Musunuru', 'district_id' => 5460],
        ['id' => 49680,'census_name' => 'Nidamarru', 'name' => 'Nidamarru', 'district_id' => 5460],
        ['id' => 50030,'census_name' => 'Nuzvid', 'name' => 'Nuzvid', 'district_id' => 5460],
        ['id' => 49650,'census_name' => 'Pedapadu', 'name' => 'Pedapadu', 'district_id' => 5460],
        ['id' => 49640,'census_name' => 'Pedavegi', 'name' => 'Pedavegi', 'district_id' => 5460],
        ['id' => 49490,'census_name' => 'Polavaram', 'name' => 'Polavaram', 'district_id' => 5460],
        ['id' => 49460,'census_name' => 'T.Narasapuram', 'name' => 'T. Narasapuram', 'district_id' => 5460],
        ['id' => 49620,'census_name' => 'Unguturu', 'name' => 'Unguturu', 'district_id' => 5460],
        ['id' => 47340,'census_name' => 'Velairpadu', 'name' => 'Velairpadu', 'district_id' => 5460],
        ['id' => 50790,'census_name' => 'Chebrolu', 'name' => 'Chebrolu', 'district_id' => 5480],
        ['id' => 50760,'census_name' => 'Duggirala', 'name' => 'Duggirala', 'district_id' => 5480],
        ['id' => 50740,'census_name' => 'Guntur', 'name' => 'Guntur East', 'district_id' => 5480],
        ['id' => 50741,'census_name' => 'Guntur', 'name' => 'Guntur West', 'district_id' => 5480],
        ['id' => 50830,'census_name' => 'Kakumanu', 'name' => 'Kakumanu', 'district_id' => 5480],
        ['id' => 50770,'census_name' => 'Kollipara', 'name' => 'Kollipara', 'district_id' => 5480],
        ['id' => 50550,'census_name' => 'Mangalagiri', 'name' => 'Mangalagiri', 'district_id' => 5480],
        ['id' => 50730,'census_name' => 'Medikonduru', 'name' => 'Medikonduru', 'district_id' => 5480],
        ['id' => 50750,'census_name' => 'Pedakakani', 'name' => 'Pedakakani', 'district_id' => 5480],
        ['id' => 50820,'census_name' => 'Pedanandipadu', 'name' => 'Pedanandipadu', 'district_id' => 5480],
        ['id' => 50720,'census_name' => 'Phirangipuram', 'name' => 'Phirangipuram', 'district_id' => 5480],
        ['id' => 50840,'census_name' => 'Ponnur', 'name' => 'Ponnur', 'district_id' => 5480],
        ['id' => 49000,'census_name' => 'Prathipadu', 'name' => 'Prathipadu', 'district_id' => 5480],
        ['id' => 50540,'census_name' => 'Tadepalle', 'name' => 'Tadepalle', 'district_id' => 5480],
        ['id' => 50560,'census_name' => 'Tadikonda', 'name' => 'Tadikonda', 'district_id' => 5480],
        ['id' => 50780,'census_name' => 'Tenali', 'name' => 'Tenali', 'district_id' => 5480],
        ['id' => 50530,'census_name' => 'Thullur', 'name' => 'Thullur', 'district_id' => 5480],
        ['id' => 50800,'census_name' => 'Vatticherukuru', 'name' => 'Vatticherukuru', 'district_id' => 5480],
        ['id' => 49040,'census_name' => 'Gandepalle', 'name' => 'Gandepalli', 'district_id' => 5451],
        ['id' => 49020,'census_name' => 'Gollaprolu', 'name' => 'Gollaprolu', 'district_id' => 5451],
        ['id' => 48980,'census_name' => 'Jaggampeta', 'name' => 'Jaggampeta', 'district_id' => 5451],
        ['id' => 49230,'census_name' => 'Kajuluru', 'name' => 'Kajuluru', 'district_id' => 5451],
        ['id' => 49130,'census_name' => 'Kakinada (Rural)', 'name' => 'Kakinada Rural', 'district_id' => 5451],
        ['id' => 49140,'census_name' => 'Kakinada (Urban)', 'name' => 'Kakinada Urban', 'district_id' => 5451],
        ['id' => 49220,'census_name' => 'Karapa', 'name' => 'Karapa', 'district_id' => 5451],
        ['id' => 48990,'census_name' => 'Kirlampudi', 'name' => 'Kirlampudi', 'district_id' => 5451],
        ['id' => 48890,'census_name' => 'Kotananduru', 'name' => 'Kotananduru', 'district_id' => 5451],
        ['id' => 49120,'census_name' => 'Kothapalle', 'name' => 'U.Kothapalli', 'district_id' => 5451],
        ['id' => 49150,'census_name' => 'Pedapudi', 'name' => 'Pedapudi', 'district_id' => 5451],
        ['id' => 49030,'census_name' => 'Peddapuram', 'name' => 'Peddapuram', 'district_id' => 5451],
        ['id' => 49110,'census_name' => 'Pithapuram', 'name' => 'Pithapuram', 'district_id' => 5451],
        ['id' => 48910,'census_name' => 'Rowthulapudi', 'name' => 'Rowthulapudi', 'district_id' => 5451],
        ['id' => 49100,'census_name' => 'Samalkota', 'name' => 'Samalkota', 'district_id' => 5451],
        ['id' => 48920,'census_name' => 'Sankhavaram', 'name' => 'Sankhavaram', 'district_id' => 5451],
        ['id' => 49300,'census_name' => 'Thallarevu', 'name' => 'Thallarevu', 'district_id' => 5451],
        ['id' => 49010,'census_name' => 'Thondangi', 'name' => 'Thondangi', 'district_id' => 5451],
        ['id' => 48900,'census_name' => 'Tuni', 'name' => 'Tuni', 'district_id' => 5451],
        ['id' => 48930,'census_name' => 'Yeleswaram', 'name' => 'Yeleswaram', 'district_id' => 5451],
        ['id' => 49330,'census_name' => 'Ainavilli', 'name' => 'Ainavilli', 'district_id' => 5452],
        ['id' => 49250,'census_name' => 'Alamuru', 'name' => 'Alumuru', 'district_id' => 5452],
        ['id' => 49400,'census_name' => 'Allavaram', 'name' => 'Allavaram', 'district_id' => 5452],
        ['id' => 49410,'census_name' => 'Amalapuram', 'name' => 'Amalapuram', 'district_id' => 5452],
        ['id' => 49350,'census_name' => 'Ambajipeta', 'name' => 'Ambajipeta', 'district_id' => 5452],
        ['id' => 49190,'census_name' => 'Atreyapuram', 'name' => 'Atreyapuram', 'district_id' => 5452],
        ['id' => 49310,'census_name' => 'I. Polavaram', 'name' => 'Island Polavaram', 'district_id' => 5452],
        ['id' => 49280,'census_name' => 'Kapileswarapuram', 'name' => 'Kapileswarapuram', 'district_id' => 5452],
        ['id' => 49430,'census_name' => 'Katrenikona', 'name' => 'Katrenikona', 'district_id' => 5452],
        ['id' => 49270,'census_name' => 'Kothapeta', 'name' => 'Kothapeta', 'district_id' => 5452],
        ['id' => 49380,'census_name' => 'Malikipuram', 'name' => 'Malikipuram', 'district_id' => 5452],
        ['id' => 49360,'census_name' => 'Mamidikuduru', 'name' => 'Mamidikuduru Mandal', 'district_id' => 5452],
        ['id' => 49200,'census_name' => 'Mandapeta', 'name' => 'Mandapeta', 'district_id' => 5452],
        ['id' => 49320,'census_name' => 'Mummidivaram', 'name' => 'Mummidivaram', 'district_id' => 5452],
        ['id' => 49340,'census_name' => 'P.Gannavaram', 'name' => 'Patha Gannavaram', 'district_id' => 5452],
        ['id' => 44950,'census_name' => 'Ramachandrapuram', 'name' => 'Ramachandrapuram', 'district_id' => 5452],
        ['id' => 49260,'census_name' => 'Ravulapalem', 'name' => 'Ravulapalem', 'district_id' => 5452],
        ['id' => 49210,'census_name' => 'Rayavaram', 'name' => 'Rayavaram', 'district_id' => 5452],
        ['id' => 49370,'census_name' => 'Razole', 'name' => 'Razole', 'district_id' => 5452],
        ['id' => 49390,'census_name' => 'Sakhinetipalle', 'name' => 'Sakhinetipalle', 'district_id' => 5452],
        ['id' => 49420,'census_name' => 'Uppalaguptam', 'name' => 'Uppalaguptam', 'district_id' => 5452],
        ['id' => 50370,'census_name' => 'Avanigadda', 'name' => 'Avanigadda', 'district_id' => 5470],
        ['id' => 50190,'census_name' => 'Bantumilli', 'name' => 'Bantumilli', 'district_id' => 5470],
        ['id' => 50040,'census_name' => 'Bapulapadu', 'name' => 'Bapulapadu', 'district_id' => 5470],
        ['id' => 50350,'census_name' => 'Challapalle', 'name' => 'Challapalli', 'district_id' => 5470],
        ['id' => 50120,'census_name' => 'Gannavaram', 'name' => 'Gannavaram', 'district_id' => 5470],
        ['id' => 50330,'census_name' => 'Ghantasala', 'name' => 'Ghantasala', 'district_id' => 5470],
        ['id' => 50210,'census_name' => 'Gudivada', 'name' => 'Gudivada', 'district_id' => 5470],
        ['id' => 50290,'census_name' => 'Gudlavalleru', 'name' => 'Gudlavalleru', 'district_id' => 5470],
        ['id' => 50310,'census_name' => 'Guduru', 'name' => 'Guduru', 'district_id' => 5470],
        ['id' => 50230,'census_name' => 'Kankipadu', 'name' => 'Kankipadu', 'district_id' => 5470],
        ['id' => 50391,'census_name' => 'Koduru', 'name' => 'Koduru', 'district_id' => 5470],
        ['id' => 50180,'census_name' => 'Kruthivennu', 'name' => 'Kruthivennu', 'district_id' => 5470],
        ['id' => 50340,'census_name' => 'Machilipatnam', 'name' => 'Machilipatnam North', 'district_id' => 5470],
        ['id' => 50341,'census_name' => 'Machilipatnam', 'name' => 'Machilipatnam South', 'district_id' => 5470],
        ['id' => 50360,'census_name' => 'Mopidevi', 'name' => 'Mopidevi', 'district_id' => 5470],
        ['id' => 50320,'census_name' => 'Movva', 'name' => 'Movva', 'district_id' => 5470],
        ['id' => 50380,'census_name' => 'Nagayalanka', 'name' => 'Nagayalanka', 'district_id' => 5470],
        ['id' => 50140,'census_name' => 'Nandivada', 'name' => 'Nandivada', 'district_id' => 5470],
        ['id' => 49290,'census_name' => 'Pamarru', 'name' => 'Pamarru', 'district_id' => 5470],
        ['id' => 50260,'census_name' => 'Pamidimukkala', 'name' => 'Pamidimukkala', 'district_id' => 5470],
        ['id' => 50300,'census_name' => 'Pedana', 'name' => 'Pedana', 'district_id' => 5470],
        ['id' => 50220,'census_name' => 'Pedaparupudi', 'name' => 'Pedaparupudi', 'district_id' => 5470],
        ['id' => 50240,'census_name' => 'Penamaluru', 'name' => 'Penamaluru', 'district_id' => 5470],
        ['id' => 50250,'census_name' => 'Thotlavalluru', 'name' => 'Thotlavalluru', 'district_id' => 5470],
        ['id' => 50270,'census_name' => 'Vuyyuru', 'name' => 'Vuyyuru', 'district_id' => 5470],
        ['id' => 52710,'census_name' => 'Adoni', 'name' => 'Adoni', 'district_id' => 5520],
        ['id' => 52740,'census_name' => 'Alur', 'name' => 'Alur', 'district_id' => 5520],
        ['id' => 52750,'census_name' => 'Aspari', 'name' => 'Aspari', 'district_id' => 5520],
        ['id' => 52560,'census_name' => 'C.Belagal', 'name' => 'C.Belagal', 'district_id' => 5520],
        ['id' => 52910,'census_name' => 'Chippagiri', 'name' => 'Chippagiri', 'district_id' => 5520],
        ['id' => 52760,'census_name' => 'Devanakonda', 'name' => 'Devanakonda', 'district_id' => 5520],
        ['id' => 52700,'census_name' => 'Gonegandla', 'name' => 'Gonegandla', 'district_id' => 5520],
        ['id' => 47110,'census_name' => 'Gudur', 'name' => 'Gudur', 'district_id' => 5520],
        ['id' => 52730,'census_name' => 'Halaharvi', 'name' => 'Halaharvi', 'district_id' => 5520],
        ['id' => 52720,'census_name' => 'Holagunda', 'name' => 'Holagunda', 'district_id' => 5520],
        ['id' => 47630,'census_name' => 'Kallur', 'name' => 'Kallur', 'district_id' => 5520],
        ['id' => 52690,'census_name' => 'Kodumur', 'name' => 'Kodumur', 'district_id' => 5520],
        ['id' => 52510,'census_name' => 'Kosigi', 'name' => 'Kosigi', 'district_id' => 5520],
        ['id' => 52520,'census_name' => 'Kowthalam', 'name' => 'Kowthalam', 'district_id' => 5520],
        ['id' => 52770,'census_name' => 'Krishnagiri', 'name' => 'Krishnagiri', 'district_id' => 5520],
        ['id' => 52590,'census_name' => 'Kurnool', 'name' => 'Kurnool Urban', 'district_id' => 5520],
        ['id' => 52591,'census_name' => 'Kurnool', 'name' => 'Kurnool Rural', 'district_id' => 5520],
        ['id' => 52920,'census_name' => 'Maddikera (East)', 'name' => 'Maddikera East', 'district_id' => 5520],
        ['id' => 52500,'census_name' => 'Mantralayam', 'name' => 'Mantralayam', 'district_id' => 5520],
        ['id' => 52550,'census_name' => 'Nandavaram', 'name' => 'Nandavaram', 'district_id' => 5520],
        ['id' => 52680,'census_name' => 'Orvakal', 'name' => 'Orvakal', 'district_id' => 5520],
        ['id' => 52900,'census_name' => 'Pattikonda', 'name' => 'Pattikonda', 'district_id' => 5520],
        ['id' => 52530,'census_name' => 'Pedda Kadubur', 'name' => 'Pedda Kadubur', 'district_id' => 5520],
        ['id' => 52930,'census_name' => 'Tuggali', 'name' => 'Tuggali', 'district_id' => 5520],
        ['id' => 50410,'census_name' => 'Veldurthi', 'name' => 'Veldurthi', 'district_id' => 5520],
        ['id' => 52540,'census_name' => 'Yemmiganur', 'name' => 'Yemmiganur', 'district_id' => 5520],
        ['id' => 49980,'census_name' => 'A.Konduru', 'name' => 'A.Konduru', 'district_id' => 5471],
        ['id' => 50080,'census_name' => 'Chandarlapadu', 'name' => 'Chandarlapadu Mandal', 'district_id' => 5471],
        ['id' => 50060,'census_name' => 'G.Konduru', 'name' => 'G.Konduru', 'district_id' => 5471],
        ['id' => 49960,'census_name' => 'Gampalagudem', 'name' => 'Gampalagudem', 'district_id' => 5471],
        ['id' => 43930,'census_name' => 'Ibrahimpatnam', 'name' => 'Ibrahimpatnam', 'district_id' => 5471],
        ['id' => 49910,'census_name' => 'Jaggayyapeta', 'name' => 'Jaggayyapeta', 'district_id' => 5471],
        ['id' => 50070,'census_name' => 'Kanchikacherla', 'name' => 'Kanchikacherla', 'district_id' => 5471],
        ['id' => 49950,'census_name' => 'Mylavaram', 'name' => 'Mylavaram', 'district_id' => 5471],
        ['id' => 49930,'census_name' => 'Nandigama', 'name' => 'Nandigama', 'district_id' => 5471],
        ['id' => 49920,'census_name' => 'Penuganchiprolu', 'name' => 'Penuganchiprolu', 'district_id' => 5471],
        ['id' => 49990,'census_name' => 'Reddigudem', 'name' => 'Reddigudem', 'district_id' => 5471],
        ['id' => 49970,'census_name' => 'Tiruvuru', 'name' => 'Tiruvuru', 'district_id' => 5471],
        ['id' => 49900,'census_name' => 'Vatsavai', 'name' => 'Vatsavai', 'district_id' => 5471],
        ['id' => 49940,'census_name' => 'Veerullapadu', 'name' => 'Veerullapadu', 'district_id' => 5471],
        ['id' => 50110,'census_name' => 'Vijayawada (Rural)', 'name' => 'Vijayawada Rural', 'district_id' => 5471],
        ['id' => 50111,'census_name' => 'Vijayawada (Rural)', 'name' => 'Vijayawada North', 'district_id' => 5471],
        ['id' => 50112,'census_name' => 'Vijayawada (Rural)', 'name' => 'Vijayawada Central', 'district_id' => 5471],
        ['id' => 50113,'census_name' => 'Vijayawada (Rural)', 'name' => 'Vijayawada East', 'district_id' => 5471],
        ['id' => 50114,'census_name' => 'Vijayawada (Rural)', 'name' => 'Vijayawada West', 'district_id' => 5471],
        ['id' => 50000,'census_name' => 'Vissannapet', 'name' => 'Vissannapeta', 'district_id' => 5471],
        ['id' => 52980,'census_name' => 'Allagadda', 'name' => 'Allagadda', 'district_id' => 5521],
        ['id' => 52880,'census_name' => 'Banaganapalle', 'name' => 'Banaganapalle', 'district_id' => 5521],
        ['id' => 52830,'census_name' => 'Bandi Atmakur', 'name' => 'Bandi Atmakur', 'district_id' => 5521],
        ['id' => 52790,'census_name' => 'Bethamcherla', 'name' => 'Bethamcherla', 'district_id' => 5521],
        ['id' => 53030,'census_name' => 'Chagalamarri', 'name' => 'Chagalamarri', 'district_id' => 5521],
        ['id' => 52890,'census_name' => 'Dhone', 'name' => 'Dhone', 'district_id' => 5521],
        ['id' => 52990,'census_name' => 'Dornipadu', 'name' => 'Dornipadu', 'district_id' => 5521],
        ['id' => 52810,'census_name' => 'Gadivemula', 'name' => 'Gadivemula', 'district_id' => 5521],
        ['id' => 52870,'census_name' => 'Gospadu', 'name' => 'Gospadu', 'district_id' => 5521],
        ['id' => 52620,'census_name' => 'Jupadu Bungalow', 'name' => 'Jupadu Bungalow', 'district_id' => 5521],
        ['id' => 52960,'census_name' => 'Koilkuntla', 'name' => 'Koilkuntla', 'district_id' => 5521],
        ['id' => 53010,'census_name' => 'Kolimigundla', 'name' => 'Kolimigundla', 'district_id' => 5521],
        ['id' => 49121,'census_name' => 'Kothapalle', 'name' => 'Kothapalle', 'district_id' => 5521],
        ['id' => 52850,'census_name' => 'Mahanandi', 'name' => 'Mahanandi', 'district_id' => 5521],
        ['id' => 52670,'census_name' => 'Midthur', 'name' => 'Midthuru', 'district_id' => 5521],
        ['id' => 52600,'census_name' => 'Nandikotkur', 'name' => 'Nandikotkur', 'district_id' => 5521],
        ['id' => 52840,'census_name' => 'Nandyal', 'name' => 'Nandyal Rural', 'district_id' => 5521],
        ['id' => 52841,'census_name' => 'Nandyal', 'name' => 'Nandyal Urban', 'district_id' => 5521],
        ['id' => 52950,'census_name' => 'Owk', 'name' => 'Owk', 'district_id' => 5521],
        ['id' => 52610,'census_name' => 'Pagidyala', 'name' => 'Pagidyala', 'district_id' => 5521],
        ['id' => 52660,'census_name' => 'Pamulapadu', 'name' => 'Pamulapadu', 'district_id' => 5521],
        ['id' => 52800,'census_name' => 'Panyam', 'name' => 'Panyam', 'district_id' => 5521],
        ['id' => 52940,'census_name' => 'Peapally', 'name' => 'Peapally', 'district_id' => 5521],
        ['id' => 52970,'census_name' => 'Rudravaram', 'name' => 'Rudravaram', 'district_id' => 5521],
        ['id' => 53000,'census_name' => 'Sanjamala', 'name' => 'Sanjamala', 'district_id' => 5521],
        ['id' => 52860,'census_name' => 'Sirvel', 'name' => 'Sirvella', 'district_id' => 5521],
        ['id' => 52640,'census_name' => 'Srisailam', 'name' => 'Srisailam', 'district_id' => 5521],
        ['id' => 53020,'census_name' => 'Uyyalawada', 'name' => 'Uyyalawada', 'district_id' => 5521],
        ['id' => 52820,'census_name' => 'Velgode', 'name' => 'Velgodu', 'district_id' => 5521],
        ['id' => 50520,'census_name' => 'Amaravathi', 'name' => 'Amaravathi', 'district_id' => 5481],
        ['id' => 50500,'census_name' => 'Atchampet', 'name' => 'Atchampet', 'district_id' => 5481],
        ['id' => 50490,'census_name' => 'Bellamkonda', 'name' => 'Bellamkonda', 'district_id' => 5481],
        ['id' => 50610,'census_name' => 'Bollapalle', 'name' => 'Bollapalle', 'district_id' => 5481],
        ['id' => 50700,'census_name' => 'Chilakaluripet
 H/O.Purushotha Patnam', 'name' => 'Chilakaluripet', 'district_id' => 5481],
        ['id' => 50450,'census_name' => 'Dachepalle', 'name' => 'Dachepalle', 'district_id' => 5481],
        ['id' => 50420,'census_name' => 'Durgi', 'name' => 'Durgi', 'district_id' => 5481],
        ['id' => 50710,'census_name' => 'Edlapadu', 'name' => 'Edlapadu', 'district_id' => 5481],
        ['id' => 50440,'census_name' => 'Gurazala', 'name' => 'Gurazala', 'district_id' => 5481],
        ['id' => 50650,'census_name' => 'Ipur', 'name' => 'Ipuru', 'district_id' => 5481],
        ['id' => 50460,'census_name' => 'Karempudi', 'name' => 'Karempudi', 'district_id' => 5481],
        ['id' => 50510,'census_name' => 'Krosuru', 'name' => 'Krosuru', 'district_id' => 5481],
        ['id' => 50400,'census_name' => 'Macherla', 'name' => 'Macharla', 'district_id' => 5481],
        ['id' => 50480,'census_name' => 'Machavaram', 'name' => 'Machavaram', 'district_id' => 5481],
        ['id' => 50680,'census_name' => 'Muppalla', 'name' => 'Muppalla', 'district_id' => 5481],
        ['id' => 50690,'census_name' => 'Nadendla', 'name' => 'Nadendla', 'district_id' => 5481],
        ['id' => 50670,'census_name' => 'Narasaraopet', 'name' => 'Narasaraopet', 'district_id' => 5481],
        ['id' => 50600,'census_name' => 'Nekarikallu', 'name' => 'Nekarikallu', 'district_id' => 5481],
        ['id' => 50630,'census_name' => 'Nuzendla', 'name' => 'Nuzendla', 'district_id' => 5481],
        ['id' => 50570,'census_name' => 'Pedakurapadu', 'name' => 'Pedakurapadu', 'district_id' => 5481],
        ['id' => 50470,'census_name' => 'Piduguralla', 'name' => 'Piduguralla', 'district_id' => 5481],
        ['id' => 50590,'census_name' => 'Rajupalem', 'name' => 'Rajupalem', 'district_id' => 5481],
        ['id' => 50430,'census_name' => 'Rentachintala', 'name' => 'Rentachintala', 'district_id' => 5481],
        ['id' => 50580,'census_name' => 'Sattenapalle', 'name' => 'Sattenapalle', 'district_id' => 5481],
        ['id' => 50640,'census_name' => 'Savalyapuram H/O Kanamarlapudi', 'name' => 'Savalyapuram', 'district_id' => 5481],
        ['id' => 50620,'census_name' => 'Vinukonda', 'name' => 'Vinukonda', 'district_id' => 5481],
        ['id' => 48150,'census_name' => 'Balijipeta', 'name' => 'Balijipeta', 'district_id' => 5430],
        ['id' => 47710,'census_name' => 'Bhamini', 'name' => 'Bhamini', 'district_id' => 5430],
        ['id' => 48110,'census_name' => 'Garugubilli', 'name' => 'Garugubilli', 'district_id' => 5430],
        ['id' => 48080,'census_name' => 'Gummalakshmipuram', 'name' => 'Gummalakshmipuram', 'district_id' => 5430],
        ['id' => 48100,'census_name' => 'Jiyyammavalasa', 'name' => 'Jiyyammavalasa', 'district_id' => 5430],
        ['id' => 48070,'census_name' => 'Komarada', 'name' => 'Komarada', 'district_id' => 5430],
        ['id' => 48090,'census_name' => 'Kurupam', 'name' => 'Kurupam', 'district_id' => 5430],
        ['id' => 48130,'census_name' => 'Makkuva', 'name' => 'Makkuva', 'district_id' => 5430],
        ['id' => 48180,'census_name' => 'Pachipenta', 'name' => 'Pachipenta', 'district_id' => 5430],
        ['id' => 47840,'census_name' => 'Palakonda', 'name' => 'Palakonda', 'district_id' => 5430],
        ['id' => 48120,'census_name' => 'Parvathipuram', 'name' => 'Parvathipuram', 'district_id' => 5430],
        ['id' => 48170,'census_name' => 'Salur', 'name' => 'Salur', 'district_id' => 5430],
        ['id' => 47700,'census_name' => 'Seethampeta', 'name' => 'Seethampeta', 'district_id' => 5430],
        ['id' => 47690,'census_name' => 'Veeraghattam', 'name' => 'Veeraghattam', 'district_id' => 5430],
        ['id' => 51160,'census_name' => 'Ardhaveedu', 'name' => 'Ardhaveedu', 'district_id' => 5491],
        ['id' => 51310,'census_name' => 'Bestawaripeta', 'name' => 'Bestawaripeta', 'district_id' => 5491],
        ['id' => 51450,'census_name' => 'Chandra Sekhara Puram', 'name' => 'Chandra Sekhara Puram', 'district_id' => 5491],
        ['id' => 51280,'census_name' => 'Chimakurthi', 'name' => 'Chimakurthi', 'district_id' => 5491],
        ['id' => 51170,'census_name' => 'Cumbum', 'name' => 'Cumbum', 'district_id' => 5491],
        ['id' => 51140,'census_name' => 'Darsi', 'name' => 'Darsi', 'district_id' => 5491],
        ['id' => 51020,'census_name' => 'Donakonda', 'name' => 'Donakonda', 'district_id' => 5491],
        ['id' => 51000,'census_name' => 'Dornala', 'name' => 'Dornala', 'district_id' => 5491],
        ['id' => 51330,'census_name' => 'Giddalur', 'name' => 'Giddalur', 'district_id' => 5491],
        ['id' => 51300,'census_name' => 'Hanumanthuni Padu', 'name' => 'Hanumanthuni Padu', 'district_id' => 5491],
        ['id' => 51360,'census_name' => 'Kanigiri', 'name' => 'Kanigiri', 'district_id' => 5491],
        ['id' => 51340,'census_name' => 'Komarolu', 'name' => 'Komarolu', 'district_id' => 5491],
        ['id' => 51190,'census_name' => 'Konakanamitla', 'name' => 'Konakanamitla', 'district_id' => 5491],
        ['id' => 51370,'census_name' => 'Kondapi', 'name' => 'Kondapi', 'district_id' => 5491],
        ['id' => 51400,'census_name' => 'Kotha Patnam', 'name' => 'Kotha Patnam', 'district_id' => 5491],
        ['id' => 51030,'census_name' => 'Kurichedu', 'name' => 'Kurichedu', 'district_id' => 5491],
        ['id' => 51270,'census_name' => 'Maddipadu', 'name' => 'Maddipadu', 'district_id' => 5491],
        ['id' => 51150,'census_name' => 'Markapur', 'name' => 'Markapuram', 'district_id' => 5491],
        ['id' => 51290,'census_name' => 'Marripudi', 'name' => 'Marripudi', 'district_id' => 5491],
        ['id' => 51130,'census_name' => 'Mundlamuru', 'name' => 'Mundlamuru', 'district_id' => 5491],
        ['id' => 51260,'census_name' => 'Naguluppala Padu', 'name' => 'Naguluppala Padu', 'district_id' => 5491],
        ['id' => 51390,'census_name' => 'Ongole', 'name' => 'Ongole Rural', 'district_id' => 5491],
        ['id' => 51391,'census_name' => 'Ongole', 'name' => 'Ongole Urban', 'district_id' => 5491],
        ['id' => 51460,'census_name' => 'Pamur', 'name' => 'Pamuru', 'district_id' => 5491],
        ['id' => 51010,'census_name' => 'Peda  Araveedu', 'name' => 'Peda Araveedu', 'district_id' => 5491],
        ['id' => 51440,'census_name' => 'Pedacherlo Palle', 'name' => 'Pedacherlo Palle', 'district_id' => 5491],
        ['id' => 51200,'census_name' => 'Podili', 'name' => 'Podili', 'district_id' => 5491],
        ['id' => 51430,'census_name' => 'Ponnaluru', 'name' => 'Ponnaluru', 'district_id' => 5491],
        ['id' => 50980,'census_name' => 'Pullalacheruvu', 'name' => 'Pullalacheruvu', 'district_id' => 5491],
        ['id' => 51320,'census_name' => 'Racherla', 'name' => 'Racherla', 'district_id' => 5491],
        ['id' => 51380,'census_name' => 'Santhanuthala Padu', 'name' => 'Santhanuthala Padu', 'district_id' => 5491],
        ['id' => 51490,'census_name' => 'Singarayakonda', 'name' => 'Singarayakonda', 'district_id' => 5491],
        ['id' => 51410,'census_name' => 'Tangutur', 'name' => 'Tangutur', 'district_id' => 5491],
        ['id' => 51180,'census_name' => 'Tarlupadu', 'name' => 'Tarlupadu', 'district_id' => 5491],
        ['id' => 51210,'census_name' => 'Thallur', 'name' => 'Thallur', 'district_id' => 5491],
        ['id' => 50990,'census_name' => 'Tripuranthakam', 'name' => 'Tripuranthakam', 'district_id' => 5491],
        ['id' => 51350,'census_name' => 'Veligandla', 'name' => 'Veligandla', 'district_id' => 5491],
        ['id' => 50970,'census_name' => 'Yerragondapalem', 'name' => 'Yerragondapalem', 'district_id' => 5491],
        ['id' => 51420,'census_name' => 'Zarugumilli', 'name' => 'Zarugumilli', 'district_id' => 5491],
        ['id' => 51670,'census_name' => 'Allur', 'name' => 'Allur, Nellore district', 'district_id' => 5500],
        ['id' => 51730,'census_name' => 'Ananthasagaram', 'name' => 'Ananthasagaram', 'district_id' => 5500],
        ['id' => 51650,'census_name' => 'Anumasamudrampeta', 'name' => 'Anumasamudrampeta', 'district_id' => 5500],
        ['id' => 45921,'census_name' => 'Atmakur', 'name' => 'Atmakuru', 'district_id' => 5500],
        ['id' => 51590,'census_name' => 'Bogole', 'name' => 'Bogolu', 'district_id' => 5500],
        ['id' => 51700,'census_name' => 'Buchireddipalem', 'name' => 'Buchireddypalem', 'district_id' => 5500],
        ['id' => 51720,'census_name' => 'Chejerla', 'name' => 'Chejerla', 'district_id' => 5500],
        ['id' => 51660,'census_name' => 'Dagadarthi', 'name' => 'Dagadarthi', 'district_id' => 5500],
        ['id' => 51620,'census_name' => 'Duttalur', 'name' => 'Duttaluru', 'district_id' => 5500],
        ['id' => 51510,'census_name' => 'Gudluru', 'name' => 'Gudluru', 'district_id' => 5500],
        ['id' => 51790,'census_name' => 'Indukurpet', 'name' => 'Indukurpet', 'district_id' => 5500],
        ['id' => 51570,'census_name' => 'Jaladanki', 'name' => 'Jaladanki', 'district_id' => 5500],
        ['id' => 51600,'census_name' => 'Kaligiri', 'name' => 'Kaligiri', 'district_id' => 5500],
        ['id' => 51740,'census_name' => 'Kaluvoya', 'name' => 'Kaluvoya', 'district_id' => 5500],
        ['id' => 45450,'census_name' => 'Kandukur', 'name' => 'Kandukur', 'district_id' => 5500],
        ['id' => 51580,'census_name' => 'Kavali', 'name' => 'Kavali', 'district_id' => 5500],
        ['id' => 51690,'census_name' => 'Kodavalur', 'name' => 'Kodavaluru', 'district_id' => 5500],
        ['id' => 51560,'census_name' => 'Kondapuram', 'name' => 'Kondapuram', 'district_id' => 5500],
        ['id' => 51780,'census_name' => 'Kovur', 'name' => 'Kovuru', 'district_id' => 5500],
        ['id' => 51500,'census_name' => 'Lingasamudram', 'name' => 'Lingasamudram', 'district_id' => 5500],
        ['id' => 51830,'census_name' => 'Manubolu', 'name' => 'Manubolu', 'district_id' => 5500],
        ['id' => 51630,'census_name' => 'Marripadu', 'name' => 'Marripadu', 'district_id' => 5500],
        ['id' => 51810,'census_name' => 'Muthukur', 'name' => 'Muttukuru', 'district_id' => 5500],
        ['id' => 51770,'census_name' => 'Nellore', 'name' => 'Nellore Urban', 'district_id' => 5500],
        ['id' => 51771,'census_name' => 'Nellore', 'name' => 'Nellore Rural', 'district_id' => 5500],
        ['id' => 51760,'census_name' => 'Podalakur', 'name' => 'Podalakuru', 'district_id' => 5500],
        ['id' => 51750,'census_name' => 'Rapur', 'name' => 'Rapuru', 'district_id' => 5500],
        ['id' => 44450,'census_name' => 'Saidapur', 'name' => 'Saidapuramu', 'district_id' => 5500],
        ['id' => 47050,'census_name' => 'Sangam', 'name' => 'Sangam', 'district_id' => 5500],
        ['id' => 51530,'census_name' => 'Seetharamapuram', 'name' => 'Sitarampuramu', 'district_id' => 5500],
        ['id' => 51800,'census_name' => 'Thotapalligudur', 'name' => 'Thotapalligudur', 'district_id' => 5500],
        ['id' => 51540,'census_name' => 'Udayagiri', 'name' => 'Udayagiri', 'district_id' => 5500],
        ['id' => 51520,'census_name' => 'Ulavapadu', 'name' => 'Ulavapadu', 'district_id' => 5500],
        ['id' => 51550,'census_name' => 'Varikuntapadu', 'name' => 'Varikuntapadu', 'district_id' => 5500],
        ['id' => 51820,'census_name' => 'Venkatachalam', 'name' => 'Venkatachalam', 'district_id' => 5500],
        ['id' => 51680,'census_name' => 'Vidavalur', 'name' => 'Vidavaluru', 'district_id' => 5500],
        ['id' => 51610,'census_name' => 'Vinjamur', 'name' => 'Vinjamuru', 'district_id' => 5500],
        ['id' => 51470,'census_name' => 'Voletivaripalem', 'name' => 'Voletivaripalem', 'district_id' => 5500],
        ['id' => 53540,'census_name' => 'Agali', 'name' => 'Agali', 'district_id' => 5531],
        ['id' => 53610,'census_name' => 'Amadagur', 'name' => 'Amadagur', 'district_id' => 5531],
        ['id' => 53510,'census_name' => 'Amarapuram', 'name' => 'Amarapuram', 'district_id' => 5531],
        ['id' => 53370,'census_name' => 'Bathalapalle', 'name' => 'Bathalapalle', 'district_id' => 5531],
        ['id' => 53450,'census_name' => 'Bukkapatnam', 'name' => 'Bukkapatnam', 'district_id' => 5531],
        ['id' => 53470,'census_name' => 'Chennekothapalle', 'name' => 'Chennekothapalle', 'district_id' => 5531],
        ['id' => 53660,'census_name' => 'Chilamathur', 'name' => 'Chilamathur', 'district_id' => 5531],
        ['id' => 53360,'census_name' => 'Dharmavaram', 'name' => 'Dharmavaram', 'district_id' => 5531],
        ['id' => 53420,'census_name' => 'Gandlapenta', 'name' => 'Gandlapenta', 'district_id' => 5531],
        ['id' => 53620,'census_name' => 'Gorantla', 'name' => 'Gorantla', 'district_id' => 5531],
        ['id' => 53520,'census_name' => 'Gudibanda', 'name' => 'Gudibanda', 'district_id' => 5531],
        ['id' => 53640,'census_name' => 'Hindupur', 'name' => 'Hindupur', 'district_id' => 5531],
        ['id' => 53430,'census_name' => 'Kadiri', 'name' => 'Kadiri', 'district_id' => 5531],
        ['id' => 53350,'census_name' => 'Kanaganapalle', 'name' => 'Kanaganapalle', 'district_id' => 5531],
        ['id' => 53460,'census_name' => 'Kothacheruvu', 'name' => 'Kothacheruvu', 'district_id' => 5531],
        ['id' => 53650,'census_name' => 'Lepakshi', 'name' => 'Lepakshi', 'district_id' => 5531],
        ['id' => 53500,'census_name' => 'Madakasira', 'name' => 'Madakasira', 'district_id' => 5531],
        ['id' => 53390,'census_name' => 'Mudigubba', 'name' => 'Mudigubba', 'district_id' => 5531],
        ['id' => 53590,'census_name' => 'Nallacheruvu', 'name' => 'Nallacheruvu', 'district_id' => 5531],
        ['id' => 53440,'census_name' => 'Nallamada', 'name' => 'Nallamada', 'district_id' => 5531],
        ['id' => 53410,'census_name' => 'Nambulipulikunta', 'name' => 'Nambulipulikunta', 'district_id' => 5531],
        ['id' => 53580,'census_name' => 'Obuladevaracheruvu', 'name' => 'Obuladevaracheruvu', 'district_id' => 5531],
        ['id' => 53550,'census_name' => 'Parigi', 'name' => 'Parigi', 'district_id' => 5531],
        ['id' => 53560,'census_name' => 'Penukonda', 'name' => 'Penukonda', 'district_id' => 5531],
        ['id' => 53570,'census_name' => 'Puttaparthi', 'name' => 'Puttaparthi', 'district_id' => 5531],
        ['id' => 53480,'census_name' => 'Ramagiri', 'name' => 'Ramagiri', 'district_id' => 5531],
        ['id' => 53490,'census_name' => 'Roddam', 'name' => 'Roddam', 'district_id' => 5531],
        ['id' => 53530,'census_name' => 'Rolla', 'name' => 'Rolla', 'district_id' => 5531],
        ['id' => 53630,'census_name' => 'Somandepalle', 'name' => 'Somandepalle', 'district_id' => 5531],
        ['id' => 53380,'census_name' => 'Tadimarri', 'name' => 'Tadimarri', 'district_id' => 5531],
        ['id' => 53400,'census_name' => 'Talupula', 'name' => 'Talupula', 'district_id' => 5531],
        ['id' => 53600,'census_name' => 'Tanakal', 'name' => 'Tanakal', 'district_id' => 5531],
        ['id' => 47980,'census_name' => 'Amadalavalasa', 'name' => 'Amadalavalasa', 'district_id' => 5420],
        ['id' => 47940,'census_name' => 'Burja', 'name' => 'Burja', 'district_id' => 5420],
        ['id' => 48060,'census_name' => 'Etcherla', 'name' => 'Etcherla', 'district_id' => 5420],
        ['id' => 47970,'census_name' => 'Ganguvarisigadam', 'name' => 'Ganguvarisigadam', 'district_id' => 5420],
        ['id' => 48010,'census_name' => 'Gara', 'name' => 'Gara', 'district_id' => 5420],
        ['id' => 47830,'census_name' => 'Hiramandalam', 'name' => 'Hiramandalam', 'district_id' => 5420],
        ['id' => 47780,'census_name' => 'Ichchapuram', 'name' => 'Ichchapuram', 'district_id' => 5420],
        ['id' => 47920,'census_name' => 'Jalumuru', 'name' => 'Jalumuru', 'district_id' => 5420],
        ['id' => 47770,'census_name' => 'Kanchili', 'name' => 'Kanchili', 'district_id' => 5420],
        ['id' => 47790,'census_name' => 'Kaviti', 'name' => 'Kaviti', 'district_id' => 5420],
        ['id' => 47910,'census_name' => 'Kotabommali', 'name' => 'Kotabommali', 'district_id' => 5420],
        ['id' => 47720,'census_name' => 'Kothuru', 'name' => 'Kothuru', 'district_id' => 5420],
        ['id' => 47870,'census_name' => 'Lakshminarsupeta', 'name' => 'Lakshminarsupeta', 'district_id' => 5420],
        ['id' => 48040,'census_name' => 'Laveru', 'name' => 'Laveru', 'district_id' => 5420],
        ['id' => 47760,'census_name' => 'Mandasa', 'name' => 'Mandasa', 'district_id' => 5420],
        ['id' => 47740,'census_name' => 'Meliaputti', 'name' => 'Meliaputti', 'district_id' => 5420],
        ['id' => 47820,'census_name' => 'Nandigam', 'name' => 'Nandigam', 'district_id' => 5420],
        ['id' => 47990,'census_name' => 'Narasannapeta', 'name' => 'Narasannapeta', 'district_id' => 5420],
        ['id' => 47750,'census_name' => 'Palasa', 'name' => 'Palasa Mandal', 'district_id' => 5420],
        ['id' => 47730,'census_name' => 'Pathapatnam', 'name' => 'Pathapatnam', 'district_id' => 5420],
        ['id' => 48000,'census_name' => 'Polaki', 'name' => 'Polaki', 'district_id' => 5420],
        ['id' => 48030,'census_name' => 'Ponduru', 'name' => 'Ponduru', 'district_id' => 5420],
        ['id' => 48050,'census_name' => 'Ranastalam', 'name' => 'Ranastalam', 'district_id' => 5420],
        ['id' => 47900,'census_name' => 'Santhabommali', 'name' => 'Santhabommali', 'district_id' => 5420],
        ['id' => 47880,'census_name' => 'Saravakota', 'name' => 'Saravakota', 'district_id' => 5420],
        ['id' => 47930,'census_name' => 'Sarubujjili', 'name' => 'Sarubujjili', 'district_id' => 5420],
        ['id' => 47800,'census_name' => 'Sompeta', 'name' => 'Sompeta', 'district_id' => 5420],
        ['id' => 48020,'census_name' => 'Srikakulam', 'name' => 'Srikakulam', 'district_id' => 5420],
        ['id' => 47890,'census_name' => 'Tekkali', 'name' => 'Tekkali', 'district_id' => 5420],
        ['id' => 47810,'census_name' => 'Vajrapukothuru', 'name' => 'Vajrapukothuru', 'district_id' => 5420],
        ['id' => 51880,'census_name' => 'Balayapalle', 'name' => 'Balayapalli', 'district_id' => 5542],
        ['id' => 53800,'census_name' => 'Buchinaidu Kandriga', 'name' => 'Buchinaidu Kandriga', 'district_id' => 5542],
        ['id' => 53840,'census_name' => 'Chandragiri', 'name' => 'Chandragiri', 'district_id' => 5542],
        ['id' => 51900,'census_name' => 'Chillakur', 'name' => 'Chilakuru', 'district_id' => 5542],
        ['id' => 53850,'census_name' => 'Chinnagottigallu', 'name' => 'Chinnagottigallu', 'district_id' => 5542],
        ['id' => 51930,'census_name' => 'Chittamur', 'name' => 'Chittamuru', 'district_id' => 5542],
        ['id' => 51860,'census_name' => 'Dakkili', 'name' => 'Dakkili', 'district_id' => 5542],
        ['id' => 51960,'census_name' => 'Doravarisatram', 'name' => 'Doravarisatramu', 'district_id' => 5542],
        ['id' => 53820,'census_name' => 'K.V.B.Puram', 'name' => 'K.V.B.Puram', 'district_id' => 5542],
        ['id' => 51910,'census_name' => 'Kota', 'name' => 'Kota', 'district_id' => 5542],
        ['id' => 54030,'census_name' => 'Nagalapuram', 'name' => 'Nagalapuram', 'district_id' => 5542],
        ['id' => 51940,'census_name' => 'Naidupet', 'name' => 'Naidupeta', 'district_id' => 5542],
        ['id' => 54000,'census_name' => 'Narayanavanam', 'name' => 'Narayanavanam', 'district_id' => 5542],
        ['id' => 51890,'census_name' => 'Ojili', 'name' => 'Ojili', 'district_id' => 5542],
        ['id' => 53960,'census_name' => 'Pakala', 'name' => 'Pakala', 'district_id' => 5542],
        ['id' => 51950,'census_name' => 'Pellakur', 'name' => 'Pellakuru', 'district_id' => 5542],
        ['id' => 54010,'census_name' => 'Pichatur', 'name' => 'Pichatur', 'district_id' => 5542],
        ['id' => 54070,'census_name' => 'Puttur', 'name' => 'Puttur', 'district_id' => 5542],
        ['id' => 53760,'census_name' => 'Renigunta', 'name' => 'Renigunta', 'district_id' => 5542],
        ['id' => 54020,'census_name' => 'Satyavedu', 'name' => 'Satyavedu', 'district_id' => 5542],
        ['id' => 53780,'census_name' => 'Srikalahasti', 'name' => 'Srikalahasti', 'district_id' => 5542],
        ['id' => 51970,'census_name' => 'Sullurpeta', 'name' => 'Sullurpeta', 'district_id' => 5542],
        ['id' => 51980,'census_name' => 'Tada', 'name' => 'Tada', 'district_id' => 5542],
        ['id' => 53790,'census_name' => 'Thottambedu', 'name' => 'Thottambedu', 'district_id' => 5542],
        ['id' => 53750,'census_name' => 'Tirupati (Rural)', 'name' => 'Tirupati Rural', 'district_id' => 5542],
        ['id' => 53830,'census_name' => 'Tirupati (Urban)', 'name' => 'Tirupati Urban', 'district_id' => 5542],
        ['id' => 53990,'census_name' => 'Vadamalapeta', 'name' => 'Vadamalapeta', 'district_id' => 5542],
        ['id' => 51920,'census_name' => 'Vakadu', 'name' => 'Vakadu', 'district_id' => 5542],
        ['id' => 53810,'census_name' => 'Varadaiahpalem', 'name' => 'Varadaiahpalem', 'district_id' => 5542],
        ['id' => 51870,'census_name' => 'Venkatagiri', 'name' => 'Venkatagiri', 'district_id' => 5542],
        ['id' => 53770,'census_name' => 'Yerpedu', 'name' => 'Yerpedu', 'district_id' => 5542],
        ['id' => 53740,'census_name' => 'Yerravaripalem', 'name' => 'Yerravaripalem', 'district_id' => 5542],
        ['id' => 48630,'census_name' => 'Anandapuram', 'name' => 'Anandapuram', 'district_id' => 5442],
        ['id' => 48650,'census_name' => 'Bheemunipatnam', 'name' => 'Bheemunipatnam', 'district_id' => 5442],
        ['id' => 48690,'census_name' => 'Gajuwaka', 'name' => 'Gajuwaka', 'district_id' => 5442],
        ['id' => 49511,'census_name' => 'Gopalapuram', 'name' => 'Gopalapatnam', 'district_id' => 5442],
        ['id' => 48670,'census_name' => 'Visakhapatnam (Urban)', 'name' => 'Maharanipeta', 'district_id' => 5442],
        ['id' => 48671,'census_name' => 'Visakhapatnam (Urban)', 'name' => 'Mulagada', 'district_id' => 5442],
        ['id' => 48640,'census_name' => 'Padmanabham', 'name' => 'Padmanabham', 'district_id' => 5442],
        ['id' => 48680,'census_name' => 'Pedagantyada', 'name' => 'Pedagantyada', 'district_id' => 5442],
        ['id' => 48620,'census_name' => 'Pendurthi', 'name' => 'Pendurthi', 'district_id' => 5442],
        ['id' => 48651,'census_name' => 'Bheemunipatnam', 'name' => 'Seethammadhara', 'district_id' => 5442],
        ['id' => 48660,'census_name' => 'Visakhapatnam (Rural)', 'name' => 'Visakhapatnam Rural', 'district_id' => 5442],
        ['id' => 48200,'census_name' => 'Badangi', 'name' => 'Badangi', 'district_id' => 5431],
        ['id' => 48400,'census_name' => 'Bhogapuram', 'name' => 'Bhogapuram', 'district_id' => 5431],
        ['id' => 48160,'census_name' => 'Bobbili', 'name' => 'Bobbili', 'district_id' => 5431],
        ['id' => 48290,'census_name' => 'Bondapalle', 'name' => 'Bondapalle', 'district_id' => 5431],
        ['id' => 48270,'census_name' => 'Cheepurupalle', 'name' => 'Cheepurupalle', 'district_id' => 5431],
        ['id' => 48230,'census_name' => 'Dattirajeru', 'name' => 'Dattirajeru', 'district_id' => 5431],
        ['id' => 48390,'census_name' => 'Denkada', 'name' => 'Denkada', 'district_id' => 5431],
        ['id' => 48250,'census_name' => 'Gajapathinagaram', 'name' => 'Gajapathinagaram', 'district_id' => 5431],
        ['id' => 48300,'census_name' => 'Gantyada', 'name' => 'Gantyada', 'district_id' => 5431],
        ['id' => 48260,'census_name' => 'Garividi', 'name' => 'Garividi', 'district_id' => 5431],
        ['id' => 48280,'census_name' => 'Gurla', 'name' => 'Gurla', 'district_id' => 5431],
        ['id' => 48350,'census_name' => 'Jami', 'name' => 'Jami', 'district_id' => 5431],
        ['id' => 48340,'census_name' => 'Kothavalasa', 'name' => 'Kothavalasa', 'district_id' => 5431],
        ['id' => 48330,'census_name' => 'Lakkavarapukota', 'name' => 'Lakkavarapukota', 'district_id' => 5431],
        ['id' => 48240,'census_name' => 'Mentada', 'name' => 'Mentada', 'district_id' => 5431],
        ['id' => 48220,'census_name' => 'Merakamudidam', 'name' => 'Merakamudidam', 'district_id' => 5431],
        ['id' => 48370,'census_name' => 'Nellimarla', 'name' => 'Nellimarla', 'district_id' => 5431],
        ['id' => 48380,'census_name' => 'Pusapatirega', 'name' => 'Pusapatirega', 'district_id' => 5431],
        ['id' => 47960,'census_name' => 'Rajam', 'name' => 'Rajam', 'district_id' => 5431],
        ['id' => 48190,'census_name' => 'Ramabhadrapuram', 'name' => 'Ramabhadrapuram', 'district_id' => 5431],
        ['id' => 47860,'census_name' => 'Regidi Amadalavalasa', 'name' => 'Regidi Amadalavalasa', 'district_id' => 5431],
        ['id' => 47950,'census_name' => 'Santhakaviti', 'name' => 'Santhakaviti', 'district_id' => 5431],
        ['id' => 48310,'census_name' => 'Srungavarapukota', 'name' => 'Srungavarapukota', 'district_id' => 5431],
        ['id' => 48210,'census_name' => 'Therlam', 'name' => 'Therlam', 'district_id' => 5431],
        ['id' => 47850,'census_name' => 'Vangara', 'name' => 'Vangara', 'district_id' => 5431],
        ['id' => 48320,'census_name' => 'Vepada', 'name' => 'Vepada', 'district_id' => 5431],
        ['id' => 48360,'census_name' => 'Vizianagaram', 'name' => 'Vizianagaram Rural', 'district_id' => 5431],
        ['id' => 48361,'census_name' => 'Vizianagaram', 'name' => 'Vizianagaram Urban', 'district_id' => 5431],
        ['id' => 49810,'census_name' => 'Achanta', 'name' => 'Achanta', 'district_id' => 5461],
        ['id' => 49750,'census_name' => 'Akividu', 'name' => 'Akividu', 'district_id' => 5461],
        ['id' => 49730,'census_name' => 'Attili', 'name' => 'Attili', 'district_id' => 5461],
        ['id' => 49840,'census_name' => 'Bhimavaram', 'name' => 'Bhimavaram', 'district_id' => 5461],
        ['id' => 49740,'census_name' => 'Ganapavaram', 'name' => 'Ganapavaram', 'district_id' => 5461],
        ['id' => 49790,'census_name' => 'Iragavaram', 'name' => 'Iragavaram', 'district_id' => 5461],
        ['id' => 49850,'census_name' => 'Kalla', 'name' => 'Kalla', 'district_id' => 5461],
        ['id' => 49860,'census_name' => 'Mogalthur', 'name' => 'Mogalthur', 'district_id' => 5461],
        ['id' => 49770,'census_name' => 'Palacoderu', 'name' => 'Palacoderu', 'district_id' => 5461],
        ['id' => 49880,'census_name' => 'Palacole', 'name' => 'Palakollu Mandal', 'district_id' => 5461],
        ['id' => 49690,'census_name' => 'Pentapadu', 'name' => 'Pentapadu', 'district_id' => 5461],
        ['id' => 49800,'census_name' => 'Penugonda', 'name' => 'Penugonda', 'district_id' => 5461],
        ['id' => 49780,'census_name' => 'Penumantra', 'name' => 'Penumantra', 'district_id' => 5461],
        ['id' => 49820,'census_name' => 'Poduru', 'name' => 'Poduru', 'district_id' => 5461],
        ['id' => 49461,'census_name' => 'T.Narasapuram', 'name' => 'T.Narasapuram', 'district_id' => 5461],
        ['id' => 49610,'census_name' => 'Tadepalligudem', 'name' => 'Tadepalligudem', 'district_id' => 5461],
        ['id' => 49720,'census_name' => 'Tanuku', 'name' => 'Tanuku', 'district_id' => 5461],
        ['id' => 49760,'census_name' => 'Undi', 'name' => 'Undi', 'district_id' => 5461],
        ['id' => 49830,'census_name' => 'Veeravasaram', 'name' => 'Veeravasaram', 'district_id' => 5461],
        ['id' => 48791,'census_name' => 'Yelamanchili', 'name' => 'Yelamanchili', 'district_id' => 5461],
        ['id' => 52270,'census_name' => 'Atlur', 'name' => 'Atlur', 'district_id' => 5510],
        ['id' => 52090,'census_name' => 'B.Kodur', 'name' => 'B.Kodur', 'district_id' => 5510],
        ['id' => 52100,'census_name' => 'Badvel', 'name' => 'Badvel', 'district_id' => 5510],
        ['id' => 52050,'census_name' => 'Brahmamgarimattam', 'name' => 'Brahmamgarimattam', 'district_id' => 5510],
        ['id' => 52340,'census_name' => 'Chakrayapet', 'name' => 'Chakrayapet', 'district_id' => 5510],
        ['id' => 52130,'census_name' => 'Chapad', 'name' => 'Chapad', 'district_id' => 5510],
        ['id' => 43560,'census_name' => 'Chennur', 'name' => 'Chennur', 'district_id' => 5510],
        ['id' => 52310,'census_name' => 'Chinthakommadinne', 'name' => 'Chinthakommadinne', 'district_id' => 5510],
        ['id' => 52030,'census_name' => 'Duvvur', 'name' => 'Duvvur', 'district_id' => 5510],
        ['id' => 52110,'census_name' => 'Gopavaram', 'name' => 'Gopavaram', 'district_id' => 5510],
        ['id' => 52150,'census_name' => 'Jammalamadugu', 'name' => 'Jammalamadugu', 'district_id' => 5510],
        ['id' => 52300,'census_name' => 'Kadapa', 'name' => 'Kadapa', 'district_id' => 5510],
        ['id' => 52070,'census_name' => 'Kalasapadu', 'name' => 'Kalasapadu', 'district_id' => 5510],
        ['id' => 52240,'census_name' => 'Kamalapuram', 'name' => 'Kamalapuram', 'district_id' => 5510],
        ['id' => 52120,'census_name' => 'Khajipet', 'name' => 'Khajipet', 'district_id' => 5510],
        ['id' => 52180,'census_name' => 'Lingala', 'name' => 'Lingala', 'district_id' => 5510],
        ['id' => 52160,'census_name' => 'Muddanur', 'name' => 'Muddanur', 'district_id' => 5510],
        ['id' => 52010,'census_name' => 'Peddamudium', 'name' => 'Peddamudium', 'district_id' => 5510],
        ['id' => 52320,'census_name' => 'Pendlimarri', 'name' => 'Pendlimarri', 'district_id' => 5510],
        ['id' => 52080,'census_name' => 'Porumamilla', 'name' => 'Porumamilla', 'district_id' => 5510],
        ['id' => 52140,'census_name' => 'Proddatur', 'name' => 'Proddatur', 'district_id' => 5510],
        ['id' => 52190,'census_name' => 'Pulivendla', 'name' => 'Pulivendla', 'district_id' => 5510],
        ['id' => 52040,'census_name' => 'S.Mydukur', 'name' => 'S.Mydukur', 'district_id' => 5510],
        ['id' => 52290,'census_name' => 'Sidhout', 'name' => 'Sidhout', 'district_id' => 5510],
        ['id' => 52170,'census_name' => 'Simhadripuram', 'name' => 'Simhadripuram', 'district_id' => 5510],
        ['id' => 52060,'census_name' => 'Sri Avadhutha Kasinayana', 'name' => 'Sri Avadhutha Kasinayana', 'district_id' => 5510],
        ['id' => 52210,'census_name' => 'Thondur', 'name' => 'Thondur', 'district_id' => 5510],
        ['id' => 52250,'census_name' => 'Vallur', 'name' => 'Vallur', 'district_id' => 5510],
        ['id' => 52220,'census_name' => 'Veerapunayunipalle', 'name' => 'Veerapunayunipalle', 'district_id' => 5510],
        ['id' => 52330,'census_name' => 'Vempalle', 'name' => 'Vempalle', 'district_id' => 5510],
        ['id' => 52200,'census_name' => 'Vemula', 'name' => 'Vemula', 'district_id' => 5510],
        ['id' => 52280,'census_name' => 'Vontimitta', 'name' => 'Vontimitta', 'district_id' => 5510],
        ['id' => 52230,'census_name' => 'Yerraguntla', 'name' => 'Yerraguntla', 'district_id' => 5510],
    ];
        foreach ($items as $item) {
            \App\Models\Mandal::create($item);
        }   
    }
}
    